export const filtersByTypeData = {
    "BOOLEAN": [
        { name: "Select condition...", value: ""},
        { name: "is true", value: "TRUE" },
        { name: "is false", value: "FALSE" },
        { name: "is null", value: "NULL" },
        { name: "is not null", value: "NOT_NULL" }
    ],
    "TEXT": [
        { name: "Select condition...", value: ""},
        { name: "is", value: "EQ_INPUT" },
        { name: "is field", value: "EQ_COLUMN" },
        { name: "contains", value: "ILIKE_INPUT" },
        { name: "contains field", value: "ILIKE_COLUMN" },
        { name: "is null", value: "NULL" },
        { name: "is not null", value: "NOT_NULL" }
    ],
    "NUMBER": [
        { name: "Select condition...", value: ""},
        { name: ">", value: "GREATER_INPUT" },
        { name: "> than field", value: "GREATER_COLUMN" },
        { name: "<", value: "LESS_INPUT" },
        { name: "< than field", value: "LESS_COLUMN" },
        { name: "=", value: "EQ_INPUT" },
        { name: "= field", value: "EQ_COLUMN" },
        { name: ">=", value: "GREATER_EQ_INPUT" },
        { name: ">= field", value: "GREATER_EQ_COLUMN" },
        { name: "<=", value: "LESS_EQ_INPUT" },
        { name: "<= field", value: "LESS_EQ_COLUMN" },
        { name: "!=", value: "DIFF_INPUT" },
        { name: "!= field", value: "DIFF_COLUMN" },
        { name: "is null", value: "NULL" },
        { name: "is not null", value: "NOT_NULL" }
    ],
    "DATE": [
        { name: "Select condition...", value: ""},
        { name: "is", value: "EQ_SELECT", select: [
            {name: "Select condition...", value: ""},
            {name: "exact date", value: "EQ_DATEPICKER"},
            {name: "today", value: "TODAY"},
            {name: "tomorrow", value: "TOMORROW"},
            {name: "yesterday", value: "YESTERDAY"},
            {name: "one week ago", value: "ONE_WEEK_AGO"},
            {name: "one week from now", value: "ONE_WEEK_FROM_NOW"},
            {name: "one month ago", value: "ONE_MONTH_AGO"},
            {name: "one month from now", value: "ONE_MONTH_FROM_NOW"},
            {name: "number of days ago", value: "DAYS_AGO_INPUT"},
            {name: "number of days from now", value: "DAYS_FROM_NOW_INPUT"},
        ]},
        { name: "is before", value: "EQ_BEFORE_SELECT", select: [
            {name: "Select condition...", value: ""},
            {name: "exact date", value: "EQ_DATEPICKER"},
            {name: "today", value: "TODAY"},
            {name: "tomorrow", value: "TOMORROW"},
            {name: "yesterday", value: "YESTERDAY"},
            {name: "one week ago", value: "ONE_WEEK_AGO"},
            {name: "one week from now", value: "ONE_WEEK_FROM_NOW"},
            {name: "one month ago", value: "ONE_MONTH_AGO"},
            {name: "one month from now", value: "ONE_MONTH_FROM_NOW"},
            {name: "number of days ago", value: "DAYS_AGO_INPUT"},
            {name: "number of days from now", value: "DAYS_FROM_NOW_INPUT"},
        ]},
        { name: "is after", value: "EQ_AFTER_SELECT", select: [
            {name: "Select condition...", value: ""},
            {name: "exact date", value: "EQ_DATEPICKER"},
            {name: "today", value: "TODAY"},
            {name: "tomorrow", value: "TOMORROW"},
            {name: "yesterday", value: "YESTERDAY"},
            {name: "one week ago", value: "ONE_WEEK_AGO"},
            {name: "one week from now", value: "ONE_WEEK_FROM_NOW"},
            {name: "one month ago", value: "ONE_MONTH_AGO"},
            {name: "one month from now", value: "ONE_MONTH_FROM_NOW"},
            {name: "number of days ago", value: "DAYS_AGO_INPUT"},
            {name: "number of days from now", value: "DAYS_FROM_NOW_INPUT"},
        ]},
        { name: "is on before", value: "EQ_ON_BEFORE_SELECT", select: [
            {name: "Select condition...", value: ""},
            {name: "exact date", value: "EQ_DATEPICKER"},
            {name: "today", value: "TODAY"},
            {name: "tomorrow", value: "TOMORROW"},
            {name: "yesterday", value: "YESTERDAY"},
            {name: "one week ago", value: "ONE_WEEK_AGO"},
            {name: "one week from now", value: "ONE_WEEK_FROM_NOW"},
            {name: "one month ago", value: "ONE_MONTH_AGO"},
            {name: "one month from now", value: "ONE_MONTH_FROM_NOW"},
            {name: "number of days ago", value: "DAYS_AGO_INPUT"},
            {name: "number of days from now", value: "DAYS_FROM_NOW_INPUT"},
        ]},
        { name: "is on after", value: "EQ_ON_AFTER_SELECT", select: [
            {name: "Select condition...", value: ""},
            {name: "exact date", value: "EQ_DATEPICKER"},
            {name: "today", value: "TODAY"},
            {name: "tomorrow", value: "TOMORROW"},
            {name: "yesterday", value: "YESTERDAY"},
            {name: "one week ago", value: "ONE_WEEK_AGO"},
            {name: "one week from now", value: "ONE_WEEK_FROM_NOW"},
            {name: "one month ago", value: "ONE_MONTH_AGO"},
            {name: "one month from now", value: "ONE_MONTH_FROM_NOW"},
            {name: "number of days ago", value: "DAYS_AGO_INPUT"},
            {name: "number of days from now", value: "DAYS_FROM_NOW_INPUT"},
        ]},
        { name: "is null", value: "NULL" },
        { name: "is not null", value: "NOT_NULL" }
    ]
}