import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import integrationService from '../services/integrations'
import styles from '../styles/Home.module.css'
import { IconAdd, IconQueries } from '../utils/svg/HomeBannerIcons'

export default function Home() {
  const [integrations, setIntegrations] = useState([])

  useEffect(() => {
    integrationService.getAllIntegrations().then(response => {
      if (!response.err) {
        setIntegrations(response.res)
      }
    })
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.banner}>
          <Link href="/integrations/create">
            <div className={styles.banner_item}>
              <IconAdd style={{ width: '70px', height: '70px' }} />
              <div>
                <h3>Create a new integration</h3>
                <p>Postgres Integration</p>
              </div>
            </div>
          </Link>
          <div className={styles.banner_item}>
            <IconQueries style={{ width: '70px', height: '70px' }} />
            <div>
              <h3>Create a new query</h3>
              <p>Consult information and generate reports.</p>
            </div>
          </div>
        </div>
        <div className={styles.container}>
          <h2>Lastest integrations</h2>
          <p>List integration order by last created</p>
          { integrations.length == 0 && <div style={{margin: '20px'}}>
            <p>😨 You don&apos;t have any integrations created yet</p>
          </div> }
          <div className={styles.integrations}>
            {integrations.map((currentIntegration) => {
              let statusColor = currentIntegration.status == 'SUCCESSFULLY' ? '#86CF4C' : '#FF5454'
              return (
                <Link href={`/integrations/${currentIntegration.code}/queries?name=${currentIntegration.name}&database=${currentIntegration.name_database}`} key={currentIntegration.code}>
                  <div className={styles.integrations_item}>
                    <div className={styles.circle_status} style={{ backgroundColor: statusColor }} />
                    <div className={styles.integration_info}>
                      <h3>{currentIntegration.name}</h3>
                      <p>{currentIntegration.name_database}</p>
                    </div>
                  </div>
                </Link>
              )
            })}
          </div>
        </div>
      </main>
    </div>
  )
}
